{% set name = "pyshacl" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 478d60eab829ed31b2bf1239dcd349122db7087e95594a93661fc9b467b2438d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshacl = pyshacl.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.9
    - python >=3.6
  run:
    - owlrl >=5.2.1
    - python >=3.6
    - rdflib >=5.0.0
    - rdflib-jsonld >=0.5.0

test:
  source_files:
    - test
  requires:
    - pytest-cov
    - pip
    # TODO: package, add (at least) run_constrained, maybe another output
    # - pyduktape2
  imports:
    - pyshacl
  commands:
    - python -m pip check
    - pyshacl --help
    - pytest --cov=pyshacl -k "not (owl_imports or js)" -vv

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
