{% set name = "pyshacl" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85072b1bf680f5fa079711e91ff7833180aa9ab5fa87c6831991c904ab26959a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshacl = pyshacl.cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - rdflib >=4.2.2
    - rdflib-jsonld
    - owlrl >=5.2.1

test:
  source_files:
    - test
  requires:
    - pytest-cov
    - pip
  imports:
    - pyshacl
  commands:
    - python -m pip check
    - pyshacl --help
    - pytest --cov=pyshacl -k "not owl_imports" -vv

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
