{% set version = "0.19.1" %}

package:
  name: pyshacl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshacl/pyshacl-{{ version }}.tar.gz
  sha256: eba29e38f6a08033ca579502140a688c0e36795b2b89f169da977197e942e369

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshacl = pyshacl.cli:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.8
    - python >=3.7
  run:
    - owlrl >=6.0.2,<7
    - packaging >=21.3
    - prettytable >=2.2.1,<3.0.0
    - python >=3.7
    - rdflib >=6.1.1,<7
  run_constrained:
    - rdflib-jsonld >=0.4.0,<0.6
    # TODO: package, maybe another output
    # - pyduktape2 >=0.4.1,<1

test:
  source_files:
    - test
  requires:
    - pytest-cov
    - pip
  imports:
    - pyshacl
  commands:
    - python -m pip check
    - pyshacl --help
    # uses pyduktape2, see above
    - python -c "__import__('pathlib').Path('test/issues/test_108.py').unlink()"
    - pytest -vv --cov=pyshacl --cov-report term-missing:skip-covered --no-cov-on-fail -k "not (owl_imports or js)" --cov-fail-under 67

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
