{% set name = "pyshacl" %}
{% set version = "0.11.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74739aa88dcdb161849f769d28e3a14ed0b01eb8256a21cc2941a27dc80e70af

build:
  noarch: python
  number: 0
  script:  {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshacl = pyshacl.cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - rdflib >=4.2.2
    - rdflib-jsonld
    - owlrl >=5.2.0

test:
  source_files:
    - test
  requires:
    - pytest-cov
  imports:
    - pyshacl
  commands:
    - pyshacl --help
    - pytest --cov=pyshacl -k "not owl_imports" -vv

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A Python validator for SHACL'
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
