travis:
  secure:
    BINSTAR_TOKEN: VYqjfQYASr0XDFgASJNyMU7xi+JQoCFrJ34NNU2P0TV74peWOxr95XdD6I5PrshbcsXMBfLcRma/+o79whBTCXACYHxgGOsMSIh1krAthcpPkQKJvy3hfbaDH3z5gRQW2UBsFBwQiZlc5I9RBc+fKNFTxcHf98Ij6+y33GmiqOJtXIJWAe+ZfT4A3cqNpM8kTDPSTENFKc2AopNMMADBG1qs20ZlanCOHkHPAS3pUxag/aYqhX6FaigcpNCwielthLZef7YRm8IPn0ro3i0g5fQHX2d+8zMAfSQi/F0PsRTANEIQ26FkXM7VLjqTq6FlVfqzKueqnGwhPMEW+Ik3fZPgkn6XQCvKR9p+BpgUlX/wU7qscqA9azbo/YRGubhYClP5XeQ+Xk2Ft2QatBfIFySHWT9XmrdeTzkcOO/byv2KMslYIaCpL0pk7yJHT1TGUj8EbV4MGOCPLlIni670n2qeq1IzsYdS+PxCUAyyH+cW1177KuHkGHL56o+viRZ/VvBp3EyyD1HXGYZLG2pQUY4Jk1uIUO+sUyoNxWNs0vmhFE2PNVYKs9lu+00wUx+bFhSklMZBBUDHHBFGKICy/jN0yI8Up5cE3CQddHEuHI4fOy8DdOfVj3MF39H2ivD5hdFYsyUSbya12osyRq1BicYAJ2zNRjKUwWSp92INwpA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
